#!/Users/corneliudumitru.sofi/Master_VU_UvA/Master_Thesis/dynamic-plugins/mc-cli/venv/bin/python3

import click
from backend_generator import BackendGenerator

@click.group()
def main():
    pass


@main.group()
def generate():
    pass


@generate.command("backend")
@click.argument("name")
@click.argument("--description", default="Micro-Component generated using mc-cli")
@click.argument("--group", default="nl.vu.dynamicplugins")
def generate_backend(name, __description, __group):
    print(f"Generating a backend component with the name: {name}")
    generator = BackendGenerator(name, __description, __group)
    generator.generate()


cli = click.CommandCollection(sources=[main])


if __name__ == '__main__':
    cli()



